<a href="https://colab.research.google.com/github/daialogue/SAD/blob/master/aula_4_apoio.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
# Start by importing some modules
import sklearn.datasets as datasets
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
#import data to variable
data = datasets.california_housing.fetch_california_housing()

#show disorganized data
data

{'DESCR': 'California housing dataset.\n\nThe original database is available from StatLib\n\n    http://lib.stat.cmu.edu/datasets/\n\nThe data contains 20,640 observations on 9 variables.\n\nThis dataset contains the average house value as target variable\nand the following input variables (features): average income,\nhousing average age, average rooms, average bedrooms, population,\naverage occupation, latitude, and longitude in that order.\n\nReferences\n----------\n\nPace, R. Kelley and Ronald Barry, Sparse Spatial Autoregressions,\nStatistics and Probability Letters, 33 (1997) 291-297.\n\n',
 'data': array([[   8.3252    ,   41.        ,    6.98412698, ...,    2.55555556,
           37.88      , -122.23      ],
        [   8.3014    ,   21.        ,    6.23813708, ...,    2.10984183,
           37.86      , -122.22      ],
        [   7.2574    ,   52.        ,    8.28813559, ...,    2.80225989,
           37.85      , -122.24      ],
        ...,
        [   1.7       ,   17.        ,    5.20554273, ...,    2.3256351 ,
           39.43      , -121.22      ],
        [   1.8672    ,   18.        ,    5.32951289, ...,    2.12320917,
           39.43      , -121.32      ],
        [   2.3886    ,   16.        ,    5.25471698, ...,    2.61698113,
           39.37      , -121.24      ]]),
 'feature_names': ['MedInc',
  'HouseAge',
  'AveRooms',
  'AveBedrms',
  'Population',
  'AveOccup',
  'Latitude',
  'Longitude'],
 'target': array([4.526, 3.585, 3.521, ..., 0.923, 0.847, 0.894])}

In [0]:



dframe = pd.DataFrame(data = data.data, columns=data.feature_names)
dframe.head()

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude
0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25

In [0]:
#dframe.aggregate(['max', 'min', 'mean']).loc[:,'AveRooms']
dframe.aggregate(['max', 'min', 'mean'])['AveRooms']

max     141.909091
min       0.846154
mean      5.429000
Name: AveRooms, dtype: float64

In [0]:
dframe.agg('mean')['Population']

1425.4767441860465

In [0]:
a = dframe.loc[:,'AveOccup'].round()

a

dframe.groupby(a).agg('mean').loc[:5,'AveRooms']

AveOccup
1.0    4.070488
2.0    5.315455
3.0    5.732835
4.0    4.852203
5.0    4.366970
Name: AveRooms, dtype: float64

In [0]:
# (dframe['Population']/10).round()*10

dframe.loc[(dframe['Population'] >1000) & (dframe['AveOccup']<2),:]

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude
7,3.1200,52.0,4.797527,1.061824,1157.0,1.788253,37.84,-122.25
14,1.9167,52.0,4.262903,1.009677,1212.0,1.954839,37.85,-122.26
39,2.5898,52.0,3.494253,1.027299,1377.0,1.978448,37.83,-122.26
95,2.0096,36.0,2.294016,1.066294,3469.0,1.493328,37.80,-122.26
96,2.8345,31.0,3.894915,1.127966,2048.0,1.735593,37.82,-122.26
98,1.2185,22.0,2.945600,1.016000,2024.0,1.619200,37.82,-122.26
99,2.6104,37.0,3.707143,1.107143,1838.0,1.875510,37.82,-122.26
100,2.4912,29.0,3.724800,1.131200,2304.0,1.843200,37.81,-122.25
101,3.2177,28.0,3.878424,1.070808,2563.0,1.712091,37.81,-122.25
104,2.8406,34.0,3.281722,1.069871,2689.0,1.503074,37.81,-122.26
109,3.9063,28.0,4.160848,1.066085,1520.0,1.895262,37.82,-122.25
111,2.6429,32.0,3.727006,1.074364,1806.0,1.767123,37.82,-122.25
112,3.0233,26.0,3.253081,0.982744,1749.0,1.437141,37.82,-122.25
116,2.4234,28.0,3.023480,1.053582,2558.0,1.540036,37.83,-122.25
117,3.0897,52.0,4.040501,1.065574,1786.0,1.722276,37.83,-122.25
151,5.3509,52.0,5.650672,1.028791,1034.0,1.984645,37.81,-122.22
163,3.2250,46.0,4.326640,1.117805,1373.0,1.838019,37.81,-122.25
164,2.9345,42.0,4.059113,1.049261,1715.0,1.689655,37.80,-122.25
165,2.1429,43.0,3.274238,1.096953,1359.0,1.882271,37.80,-122.25
167,1.3929,29.0,3.192755,1.117723,1335.0,1.727038,37.80,-122.25
425,4.2813,52.0,5.410628,1.043478,1232.0,1.983897,37.88,-122.27
448,2.5430,46.0,4.477037,1.031111,1293.0,1.915556,37.87,-122.28
450,2.1907,52.0,3.199772,1.061644,1372.0,1.566210,37.88,-122.27
452,2.5200,37.0,4.251623,1.107143,1152.0,1.870130,37.88,-122.27
461,1.1859,52.0,2.922023,1.051633,1721.0,1.813488,37.87,-122.26
462,1.7464,35.0,3.218000,1.108000,1675.0,1.675000,37.87,-122.27
468,2.5370,44.0,3.561010,1.058906,1382.0,1.938289,37.87,-122.29
485,1.6307,35.0,2.962687,1.001148,3276.0,1.880597,37.86,-122.26
486,2.9044,52.0,4.404282,1.047859,1493.0,1.880353,37.86,-122.26
496,3.2619,52.0,4.792053,1.017219,1508.0,1.997351,37.85,-122.26
...,...,...,...,...,...,...,...,...
18423,2.0288,20.0,4.567204,1.036290,1231.0,1.654570,37.25,-121.81
18437,3.7844,4.0,3.958796,1.228209,1213.0,1.922345,37.25,-121.87
18566,2.6506,14.0,4.813486,0.997131,1350.0,1.936872,36.92,-121.74
18646,2.1771,15.0,4.392496,1.134199,1306.0,1.884560,36.97,-121.99
18652,2.5610,27.0,4.233862,1.057143,1808.0,1.913228,36.96,-121.97
18659,3.0905,21.0,4.674635,1.103586,1486.0,1.973440,36.98,-121.94
18671,3.5112,19.0,5.336226,1.184382,1807.0,1.959870,36.97,-121.91
18707,1.3329,40.0,4.280220,1.020879,1782.0,1.958242,40.58,-122.40
18719,1.7227,14.0,4.452425,1.056903,2101.0,1.959888,40.61,-122.38
18720,2.4079,7.0,4.035853,1.041309,2557.0,1.992985,40.60,-122.37
18880,1.1835,30.0,3.350505,1.068687,1794.0,1.812121,38.10,-122.26
18910,1.6368,28.0,4.357447,1.120567,1375.0,1.950355,38.13,-122.26
18917,2.6466,14.0,4.893543,1.024433,1083.0,1.890052,38.04,-122.15
18986,2.8357,17.0,5.308256,1.059254,2899.0,1.930093,38.37,-121.94
19064,1.9487,25.0,4.670677,1.075188,1262.0,1.897744,38.34,-122.44
19068,2.5658,14.0,4.815484,1.091613,1277.0,1.647742,38.29,-122.47
19077,3.5625,8.0,5.440171,1.055556,1657.0,1.770299,38.27,-122.49
19149,2.3464,11.0,3.492212,1.088785,1203.0,1.873832,38.35,-122.71
19182,3.9375,10.0,5.629108,1.034429,1132.0,1.771518,38.43,-122.58
19229,2.8250,16.0,4.648464,1.011945,1124.0,1.918089,38.48,-122.66
19242,2.4922,23.0,4.764706,1.041746,1052.0,1.996205,38.52,-122.78
19258,1.7220,14.0,3.432792,1.113737,1026.0,1.515510,38.46,-122.73
20273,3.6875,18.0,5.100000,1.231405,2164.0,1.788430,34.17,-119.23
20298,2.9832,22.0,4.718978,1.019708,2694.0,1.966423,34.18,-119.20
20346,3.1446,13.0,3.284815,1.039339,2257.0,1.775767,34.22,-119.06
20347,4.2917,5.0,4.890983,0.966353,1317.0,1.772544,34.19,-119.00
20368,2.8958,17.0,4.392906,0.976808,1381.0,1.884038,34.18,-118.91
20379,4.2857,16.0,5.273011,1.140406,1227.0,1.914197,34.15,-118.83
20412,3.3703,16.0,4.396854,1.045977,3232.0,1.955233,34.19,-118.88
20534,1.7257,18.0,3.461538,1.006119,2248.0,1.965035,38.56,-121.74

In [0]:
vals= (dframe['HouseAge']/5).round()*5
vals



dframe.groupby(dframe['AveOccup'].round()).aggregate('mean').loc[:5,'AveRooms']

0        40.0
1        20.0
2        50.0
3        50.0
4        50.0
5        50.0
6        50.0
7        50.0
8        40.0
9        50.0
10       50.0
11       50.0
12       50.0
13       50.0
14       50.0
15       50.0
16       50.0
17       50.0
18       50.0
19       50.0
20       40.0
21       40.0
22       50.0
23       50.0
24       50.0
25       40.0
26       50.0
27       50.0
28       50.0
29       50.0
         ...
20610    30.0
20611    25.0
20612    25.0
20613    30.0
20614    25.0
20615    25.0
20616    15.0
20617    20.0
20618    25.0
20619    20.0
20620    40.0
20621    35.0
20622    20.0
20623    30.0
20624    15.0
20625    35.0
20626    35.0
20627     5.0
20628    20.0
20629    30.0
20630    10.0
20631    15.0
20632    15.0
20633    25.0
20634    30.0
20635    25.0
20636    20.0
20637    15.0
20638    20.0
20639    15.0
Name: HouseAge, Length: 20640, dtype: float64